### ISSUE TITLE
【咨询】没有找到任何驱动，似乎你的系统不支持或驱动安装失败。

### ISSUE THREAD

**Issue by ghost** [shidahuilang/pve#4]
pve版本8.1.4
你没有添加过温度显示，退出脚本.

 按任意键继续...  
              PVE优化脚本     
┌──────────────────────────────────────────┐
    1. 一键优化PVE(换源、去订阅等)
    2. 配置PCI硬件直通
    3. 设置CPU电源模式
    4. 添加CPU、主板、硬盘温度显示
    5. 删除CPU、主板、硬盘温度显示
├──────────────────────────────────────────┤
    0. 退出
└──────────────────────────────────────────┘

 请选择: [4]
pve版本8.1.4
lm-sensors 未安装，开始安装软件包
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package sysstat is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package lm-sensors
E: Unable to locate package nvme-cli
E: Package 'sysstat' has no installation candidate
E: Unable to locate package linux-cpupower
chmod: cannot access '/usr/sbin/nvme': No such file or directory
chmod: cannot access '/usr/sbin/hddtemp': No such file or directory
chmod: cannot access '/usr/sbin/turbostat': No such file or directory
Failed to set permissions for /usr/sbin/turbostat
软件包安装完成，检测硬件信息
./pve.sh: line 579: sensors-detect: command not found
没有找到任何驱动，似乎你的系统不支持或驱动安装失败。

是不支持吗？

**Comment by shidahuilang** [comment]
应该是你的源有问题，软件没有安装成功
